### ISSUE TITLE
[Bug]: Transfer onClick UX Handling 

### ISSUE THREAD

**Issue by Zack-Xb** [AvailX/avail-wallet#30]
### Contact Details

None

### What happened?

From user "i noticed i was able to hit send multiple times while the transfer is in progress - i feel like i should be taken to a confirmation screen or activity screen or something to prevent duplicate sends." 

We must guide the user to home or activity page so they can see the transaction is now processing. 

### Version

v0.0.1-alpha

### What operating system are you using?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-blc** [comment]
### Issue Fixed
The app navigates to the activity page now when hit send. 

### Fix
Added a `navigate` to the Activity window once the send button clicks. 

`NOTE - ISSUE WILL BE CLOSED ONCE THE CHANGES ARE FINALISED AND MERGED`
