### ISSUE TITLE
[Feature]: Browser Link resolver 

### ISSUE THREAD

**Issue by Zack-Xb** [AvailX/avail-wallet#34]
### Contact Details

None

### What happened?

If a person writes `arcane.finance` for example this should go to `https://arcane.finance` automatically. 

### Version

v0.0.1-alpha

### What operating system are you using?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-blc** [comment]
### Issue Resolved 
The browser now redirects to the resolved URL if typed without `http://` or `https://`

### Fix 
Logic is placed to check if the URL typed has the resolver, if not format the input URL or string.

`NOTE - ISSUE WILL BE CLOSED ONCE THE CHANGES ARE FINALISED AND MERGED`
