### ISSUE TITLE
Add navigation buttons/options at wallet creation page and other reasonable pages

### ISSUE THREAD

**Issue by dev-blc** [AvailX/avail-wallet#46]
### Contact Details

None

### What happened?

"It'd be good to have a go back button at various steps of the app. Like for example, when testing users on seed phrases, there is no go back button when I accidentally proceeded through without saving my phrases!" - JK | Apybara 
Feedback submitted in telegram.

### Version

v0.0.1-alpha

### What operating system are you using?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zack-Xb** [comment]
Avail logo is currently back button. This will be made more visible or changed to back arrow icon.
